// Générateur de Civilisation - Base de données des combinaisons
// Organisé selon un ordre logique pour éviter tout blocage

const COMBINATIONS = {
    // ===== ÈRE 1 : TRIBALE (L'AUBE) =====

    // Section 1.1 : Le Monde (Découvertes de base)
    "Humain+Terre": { result: "Trace", icon: "👣", narration: "Les premiers pas de l'humanité marquent la terre. L'histoire commence." },
    "Terre+Terre": { result: "Pierre", icon: "🗿", narration: "Les pierres, premières outils de l'humanité." },
    "Terre+Trace": { result: "Forêt", icon: "🌳", narration: "En explorant, l'humanité découvre les vastes forêts." },
    "Terre+Pierre": { result: "Montagne", icon: "⛰️", narration: "Les montagnes s'élèvent, majestueuses et intimidantes." },
    "Montagne+Terre": { result: "Rivière", icon: "🏞️", narration: "Des montagnes coule l'eau des rivières." },
    "Rivière+Humain": { result: "Eau", icon: "💧", narration: "L'eau est découverte, source de toute vie." },
    "Eau+Eau": { result: "Océan", icon: "🌊", narration: "Les eaux se rassemblent en vastes océans infinis." },
    "Terre+Eau": { result: "Boue", icon: "💩", narration: "L'eau rencontre la terre, créant la boue primitive." },
    "Pierre+Eau": { result: "Sable", icon: "🏖️", narration: "L'eau érode la pierre, créant le sable fin." },
    "Sable+Sable": { result: "Désert", icon: "🏜️", narration: "Le sable s'étend à l'infini, formant des déserts hostiles." },
    "Forêt+Humain": { result: "Bois", icon: "🪵", narration: "Les arbres deviennent ressource. Le bois, matériau de base." },
    "Forêt+Forêt": { result: "Animal", icon: "🦌", narration: "Dans les forêts vivent les animaux sauvages." },
    "Forêt+Terre": { result: "Baies", icon: "🍓", narration: "Les fruits sauvages nourrissent les premiers cueilleurs." },
    "Forêt+Eau": { result: "Plante", icon: "🌱", narration: "Les plantes poussent là où il y a eau et terre." },
    "Plante+Humain": { result: "Graine", icon: "🌾", narration: "Les graines sont récoltées, promesse de futures récoltes." },
    "Humain+Montagne": { result: "Ciel", icon: "🔭", narration: "De la montagne, le peuple lève les yeux vers le ciel infini." },
    "Ciel+Pierre": { result: "Lune", icon: "🌙", narration: "La lune brille dans le ciel nocturne." },
    "Ciel+Ciel": { result: "Nuit", icon: "🌃", narration: "La nuit tombe, mystérieuse et effrayante." },

    // Section 1.2 : Le Foyer (Maîtrise)
    "Pierre+Pierre": { result: "Étincelle", icon: "✨", narration: "Deux pierres s'entrechoquent. Une étincelle jaillit dans la nuit." },
    "Étincelle+Bois": { result: "Feu", icon: "🔥", narration: "L'étincelle enflamme le bois. Le feu, conquis ! L'humanité ne sera plus jamais dans l'obscurité." },
    "Feu+Humain": { result: "Campement", icon: "🏕️", narration: "Autour du feu, le campement devient le cœur de la vie tribale." },
    "Feu+Bois": { result: "Chaleur", icon: "♨️", narration: "Le feu produit une chaleur réconfortante contre le froid." },
    "Feu+Nuit": { result: "Lumière", icon: "💡", narration: "Le feu illumine la nuit, repoussant les ténèbres." },
    "Feu+Ciel": { result: "Soleil", icon: "☀️", narration: "Le soleil, le feu du ciel qui donne la vie." },
    "Terre+Feu": { result: "Volcan", icon: "🌋", narration: "La terre crache le feu. Les volcans, terrifiants et majestueux." },
    "Volcan+Eau": { result: "Source Chaude", icon: "♨️", narration: "L'eau chauffée par le volcan crée des sources bienfaisantes." },
    "Volcan+Terre": { result: "Obsidienne", icon: "🌋", narration: "La roche volcanique refroidie forme l'obsidienne, noire et tranchante." },
    "Trace+Humain": { result: "Grotte", icon: "🏞️", narration: "En suivant les traces, on trouve un abri dans les grottes." },
    "Feu+Grotte": { result: "Foyer", icon: "🏠", narration: "La grotte avec un feu devient un foyer, le premier vrai chez-soi." },
    "Pierre+Humain": { result: "Outil Primitif", icon: "🛠️", narration: "La pierre taillée devient outil. L'homo habilis maîtrise la matière." },
    "Outil Primitif+Pierre": { result: "Silex Taillé", icon: "🔪", narration: "Le silex, taillé avec précision, devient lame acérée." },
    "Obsidienne+Outil Primitif": { result: "Lame d'Obsidienne", icon: "🔪", narration: "L'obsidienne, plus tranchante que le silex, devient l'arme ultime." },
    "Boue+Feu": { result: "Argile Cuite", icon: "🏺", narration: "La boue chauffée durcit. La céramique primitive naît." },
    "Argile Cuite+Eau": { result: "Récipient", icon: "🏺", narration: "L'argile formée devient récipient. Le stockage est possible." },

    // Section 1.3 : La Tribu (Vie sociale)
    "Humain+Humain": { result: "Son", icon: "🗣️", narration: "Les humains communiquent par des sons primitifs." },
    "Humain+Son": { result: "Cri", icon: "📢", narration: "Le premier cri résonne. La communication primitive commence." },
    "Cri+Humain": { result: "Langage", icon: "🗣️", narration: "Les cris deviennent mots. Le langage, ce pouvoir qui sépare l'homme de la bête, naît." },
    "Humain+Langage": { result: "Famille", icon: "👨‍👩‍👧‍👦", narration: "Le langage permet de nommer les liens. La famille naît." },
    "Famille+Famille": { result: "Clan", icon: "👥", narration: "Les familles s'unissent pour former des clans. La société tribale émerge." },
    "Campement+Clan": { result: "Tribu", icon: "🤝", narration: "Le clan autour du campement forme une tribu unie." },
    "Animal+Grotte": { result: "Prédateur", icon: "🐻", narration: "Dans les grottes se cachent les prédateurs dangereux." },
    "Prédateur+Humain": { result: "Mort", icon: "💀", narration: "Les prédateurs apportent la mort aux humains." },
    "Mort+Famille": { result: "Deuil", icon: "😢", narration: "La mort frappe. Le deuil, première émotion collective face à la perte." },
    "Deuil+Pierre": { result: "Tombe", icon: "⚰️", narration: "Les morts sont enterrés sous des pierres. Le culte funéraire naît." },
    "Tombe+Famille": { result: "Souvenir", icon: "🏵️", narration: "La mémoire des morts perdure. Le souvenir transcende la mort." },
    "Nuit+Humain": { result: "Peur", icon: "😨", narration: "La nuit apporte la peur de l'inconnu." },
    "Peur+Feu": { result: "Sécurité", icon: "🛡️", narration: "Le feu éloigne les prédateurs. La peur se transforme en sécurité." },
    "Peur+Langage": { result: "Superstition", icon: "👻", narration: "La peur de l'inconnu engendre les superstitions primitives." },
    "Superstition+Humain": { result: "Rituel", icon: "🕯️", narration: "Les rituels apaisent les esprits et rassemblent la tribu." },
    "Rituel+Mort": { result: "Culte des Ancêtres", icon: "👻", narration: "Les ancêtres sont vénérés. Leur sagesse guide les vivants." },
    "Culte des Ancêtres+Humain": { result: "Chaman", icon: "🧙", narration: "Le chaman, intermédiaire entre les mondes, naît dans la tribu." },
    "Chaman+Plante": { result: "Herbes", icon: "🌿", narration: "Le chaman découvre les plantes médicinales." },
    "Rituel+Chaman": { result: "Transe", icon: "🌀", narration: "Le chaman entre en transe pour communiquer avec les esprits." },
    "Transe+Chaman": { result: "Vision", icon: "🔮", narration: "Les visions du chaman guident la tribu." },
    "Vision+Langage": { result: "Mythe", icon: "📜", narration: "Les visions deviennent mythes transmis oralement." },
    "Mythe+Tribu": { result: "Croyance", icon: "🌌", narration: "Les mythes forment un système de croyances." },
    "Langage+Son": { result: "Chant", icon: "🎶", narration: "Les mots deviennent mélodie. Le chant, première musique." },
    "Pierre+Son": { result: "Percussion", icon: "🥁", narration: "Frapper la pierre crée des rythmes primitifs." },
    "Chant+Percussion": { result: "Musique", icon: "🎶", narration: "Chant et percussion s'unissent en musique." },
    "Musique+Rituel": { result: "Danse", icon: "💃", narration: "Le corps accompagne la musique dans la danse rituelle." },
    "Danse+Feu": { result: "Célébration", icon: "🎊", narration: "Autour du feu, la tribu danse et célèbre." },
    "Boue+Chaleur": { result: "Ocre", icon: "🎨", narration: "La boue chauffée produit des pigments colorés." },
    "Ocre+Eau": { result: "Peinture", icon: "🎨", narration: "L'ocre mélangée à l'eau devient peinture." },
    "Grotte+Peinture": { result: "Art Rupestre", icon: "🎨", narration: "Les murs des grottes se parent de peintures. L'art naît de la main humaine." },
    "Tribu+Tribu": { result: "Troc", icon: "🤝", narration: "Les tribus échangent des biens. Le troc, premier commerce." },

    // Section 1.4 : La Survie (Outils et Subsistance)
    "Outil Primitif+Bois": { result: "Lance", icon: "🌲", narration: "Le bois et la pierre s'assemblent. La lance, arme de chasse redoutable." },
    "Bois+Pierre": { result: "Hache", icon: "🪓", narration: "La hache primitive permet d'abattre les arbres et de façonner le bois." },
    "Humain+Animal": { result: "Chasse", icon: "🦌", narration: "La traque commence. L'homme devient chasseur." },
    "Chasse+Lance": { result: "Nourriture", icon: "🍖", narration: "La chasse réussie apporte la viande, source de protéines." },
    "Nourriture+Feu": { result: "Viande Cuite", icon: "🥩", narration: "Le feu transforme la viande. La cuisson révolutionne l'alimentation." },
    "Viande Cuite+Humain": { result: "Force", icon: "💪", narration: "La viande cuite nourrit mieux. Les humains deviennent plus forts." },
    "Chasse+Silex Taillé": { result: "Peau de Bête", icon: "👕", narration: "Les peaux sont prélevées sur les animaux chassés." },
    "Peau de Bête+Humain": { result: "Vêtement", icon: "👖", narration: "Les peaux cousues protègent du froid. Le vêtement naît." },
    "Vêtement+Chaleur": { result: "Protection", icon: "🛡️", narration: "Vêtus et au chaud, les humains survivent aux hivers." },
    "Chasse+Nourriture": { result: "Os", icon: "🦴", narration: "Les os des animaux chassés deviennent ressources." },
    "Os+Outil Primitif": { result: "Aiguille", icon: "🪡", narration: "Les os taillés deviennent aiguilles pour coudre." },
    "Aiguille+Peau de Bête": { result: "Vêtement Cousu", icon: "👗", narration: "L'aiguille permet de coudre des vêtements ajustés." },
    "Plante+Plante": { result: "Fibre", icon: "🧵", narration: "Certaines plantes produisent des fibres solides." },
    "Fibre+Fibre": { result: "Corde", icon: "🧶", narration: "Les fibres tressées deviennent cordes." },
    "Corde+Bois": { result: "Piège", icon: "🪤", narration: "La corde et le bois forment des pièges ingénieux." },
    "Piège+Chasse": { result: "Petit Gibier", icon: "🐇", narration: "Les pièges capturent le petit gibier." },
    "Eau+Humain": { result: "Pêche", icon: "🐟", narration: "Dans l'eau, on apprend à pêcher." },
    "Pêche+Bois": { result: "Harpon", icon: "🔱", narration: "Un bâton pointu devient harpon de pêche." },
    "Pêche+Corde": { result: "Filet de Pêche", icon: "🎣", narration: "Les cordes tissées forment des filets de pêche." },
    "Animal+Campement": { result: "Loup", icon: "🐺", narration: "Les loups rôdent autour des campements." },
    "Loup+Campement": { result: "Chien", icon: "🐕", narration: "Le loup apprivoisé devient le chien, premier animal domestique." },
    "Plante+Eau": { result: "Champignon", icon: "🍄", narration: "Les champignons poussent dans l'humidité." },
    "Champignon+Humain": { result: "Poison", icon: "☠️", narration: "Certains champignons sont toxiques et mortels." },
    "Poison+Lance": { result: "Lance Empoisonnée", icon: "🏹", narration: "Le poison sur la lance rend la chasse plus efficace." },
    "Bois+Bois": { result: "Hutte", icon: "🛖", narration: "Les branches assemblées forment les premières huttes." },
    "Grotte+Campement": { result: "Abri Permanent", icon: "🛖", narration: "L'abri devient permanent. La sédentarisation commence timidement." },
    "Abri Permanent+Abri Permanent": { result: "Hameau", icon: "🏠", narration: "Les abris se multiplient. Le premier hameau apparaît." },
    "Clan+Humain": { result: "Ancien", icon: "👴", narration: "Les anciens, dépositaires de la sagesse, guident le clan." },
    "Ancien+Souvenir": { result: "Sagesse Tribale", icon: "🧠", narration: "La sagesse se transmet oralement de génération en génération." },
    "Baies+Humain": { result: "Cueillette", icon: "🍇", narration: "La cueillette systématique commence, première forme d'exploitation de la nature." },
    "Cueillette+Chasse": { result: "Chasseur-Cueilleur", icon: "🏹", narration: "L'homme combine chasse et cueillette. Le mode de vie paléolithique s'installe." },
    "Superstition+Forêt": { result: "Esprit de la Forêt", icon: "🌳", narration: "Les arbres deviennent sacrés, habités par des esprits." },
    "Superstition+Eau": { result: "Esprit de l'Eau", icon: "💧", narration: "L'eau est peuplée d'esprits mystérieux." },
    "Esprit de la Forêt+Rituel": { result: "Animisme", icon: "🙏", narration: "Tout est vivant, tout a une âme. L'animisme, première religion de l'humanité." },
    "Rituel+Campement": { result: "Cohésion Sociale", icon: "🤝", narration: "Les rituels renforcent les liens. La cohésion sociale s'installe." },
    "Terre+Humain": { result: "Plaines", icon: "🌄", narration: "Les plaines s'étendent, offrant l'espace pour grandir." },

    // ===== ÈRE 2 : AGRICOLE (LE RÉVEIL) =====

    // Section 2.1 : La Sédentarisation
    "Graine+Terre": { result: "Agriculture", icon: "🚜", narration: "Les graines plantées germent. La révolution néolithique commence. L'homme ne chasse plus, il cultive." },
    "Agriculture+Terre": { result: "Champ", icon: "🏞️", narration: "Les champs s'étendent. La terre est domptée." },
    "Agriculture+Humain": { result: "Fermier", icon: "🧑‍🌾", narration: "Le chasseur devient agriculteur. Un nouveau mode de vie naît." },
    "Champ+Eau": { result: "Irrigation", icon: "🛶", narration: "L'eau canalisée nourrit les cultures. L'irrigation primitive transforme les déserts." },
    "Irrigation+Champ": { result: "Récolte", icon: "🌽", narration: "Les champs irrigués produisent des récoltes abondantes." },
    "Récolte+Humain": { result: "Surplus de Nourriture", icon: "🍞", narration: "Pour la première fois, l'humanité produit plus qu'elle ne consomme. Le surplus change tout." },
    "Surplus de Nourriture+Récipient": { result: "Stockage", icon: "📦", narration: "Les surplus sont stockés pour l'hiver. La prévoyance apparaît." },
    "Stockage+Hameau": { result: "Village", icon: "🏘️", narration: "Le surplus permet la sédentarisation. Le village permanent naît." },
    "Stockage+Village": { result: "Grenier", icon: "🏛️", narration: "Les greniers collectifs sécurisent l'approvisionnement du village." },
    "Eau+Terre": { result: "Puits", icon: "💧", narration: "Les puits creusés apportent l'eau au village." },
    "Puits+Village": { result: "Eau Potable", icon: "💧", narration: "L'eau potable accessible améliore la santé publique." },

    // Section 2.2 : Élevage et Nouvelles Techniques
    "Animal+Champ": { result: "Clôture", icon: "🚧", narration: "Les animaux sont parqués. La domestication commence." },
    "Clôture+Animal": { result: "Bétail", icon: "🐄", narration: "Les animaux sauvages deviennent bétail domestique." },
    "Bétail+Humain": { result: "Éleveur", icon: "🧑‍🌾", narration: "L'élevage devient un métier. L'homme et l'animal cohabitent." },
    "Bétail+Plante": { result: "Engrais", icon: "💩", narration: "Le fumier enrichit la terre. Le cycle agricole se perfectionne." },
    "Engrais+Champ": { result: "Récolte Abondante", icon: "🌽", narration: "Les champs fertilisés produisent des récoltes extraordinaires." },
    "Bétail+Fermier": { result: "Lait", icon: "🥛", narration: "Le lait animal nourrit les humains. Une nouvelle source de protéines." },
    "Bétail+Bois": { result: "Charrue", icon: "🔱", narration: "La charrue tirée par les bœufs révolutionne l'agriculture." },
    "Charrue+Champ": { result: "Champ Labouré", icon: "🚜", narration: "Les champs labourés sont plus productifs. L'agriculture intensive naît." },
    "Bétail+Force": { result: "Animal de Trait", icon: "🐎", narration: "Les animaux tirent les charges. Le transport se développe." },
    "Hache+Bois": { result: "Roue", icon: "🎡", narration: "Le bois façonné à la hache devient roue, invention révolutionnaire." },
    "Roue+Animal de Trait": { result: "Chariot", icon: "🛒", narration: "Le chariot permet de transporter marchandises et personnes." },
    "Bétail+Vêtement": { result: "Laine", icon: "🐑", narration: "La laine des moutons devient textile." },
    "Laine+Humain": { result: "Fil", icon: "🧵", narration: "La laine est filée. Le textile commence." },
    "Fil+Fil": { result: "Tissu", icon: "👕", narration: "Les fils tissés forment des tissus. Les vêtements se raffinent." },
    "Tissu+Vêtement": { result: "Vêtement Tissé", icon: "👗", narration: "Les vêtements tissés remplacent les peaux de bêtes." },
    "Récolte+Pierre": { result: "Farine", icon: "🌾", narration: "Le grain moulu devient farine." },
    "Farine+Eau": { result: "Pâte", icon: "🍞", narration: "La farine et l'eau forment une pâte malléable." },
    "Pâte+Feu": { result: "Pain", icon: "🥖", narration: "La pâte cuite devient pain. L'aliment de base de l'humanité naît." },
    "Graine+Montagne": { result: "Vigne", icon: "🍇", narration: "La vigne pousse sur les coteaux ensoleillés." },
    "Vigne+Récipient": { result: "Vin", icon: "🍷", narration: "Le raisin fermenté devient vin." },
    "Récolte+Eau": { result: "Bière", icon: "🍺", narration: "Le grain fermenté produit la bière." },

    // Section 2.3 : Société Organisée
    "Surplus de Nourriture+Humain": { result: "Artisan", icon: "⚒️", narration: "Libérés de la quête de nourriture, certains se spécialisent. L'artisanat naît." },
    "Artisan+Bois": { result: "Menuisier", icon: "🪑", narration: "Le menuisier façonne le bois en meubles et outils." },
    "Artisan+Argile Cuite": { result: "Potier", icon: "🏺", narration: "Le potier maîtrise l'argile. Les céramiques se raffinent." },
    "Potier+Argile Cuite": { result: "Céramique", icon: "🏺", narration: "La céramique devient art et ustensile du quotidien." },
    "Artisan+Tissu": { result: "Tailleur", icon: "🧵", narration: "Le tailleur confectionne des vêtements sur mesure." },
    "Village+Village": { result: "Communauté", icon: "🤝", narration: "Les villages s'unissent en communautés plus larges." },
    "Communauté+Surplus de Nourriture": { result: "Marché", icon: "📈", narration: "Les surplus sont échangés au marché. L'économie naît." },
    "Marché+Troc": { result: "Échange", icon: "💰", narration: "Le troc organisé devient système d'échange structuré." },
    "Trace+Village": { result: "Sentier", icon: "🛣️", narration: "Les sentiers relient les villages entre eux." },
    "Sentier+Village": { result: "Route", icon: "🛣️", narration: "Les sentiers élargis deviennent routes." },
    "Chariot+Route": { result: "Transport", icon: "🚚", narration: "Les chariots sur les routes créent un réseau de transport." },
    "Transport+Marché": { result: "Caravane", icon: "🚚", narration: "Les caravanes marchandes parcourent de longues distances." },
    "Village+Croyance": { result: "Autel", icon: "⛩️", narration: "Un autel est érigé pour honorer les dieux." },
    "Autel+Chaman": { result: "Prêtre", icon: "🧙", narration: "Le chaman devient prêtre. La religion s'organise." },
    "Prêtre+Croyance": { result: "Religion", icon: "🙏", narration: "La religion organisée structure la société et donne sens à l'existence." },
    "Religion+Village": { result: "Temple", icon: "⛩️", narration: "Les temples s'élèvent, maisons des dieux." },
    "Temple+Rituel": { result: "Cérémonie", icon: "🛐", narration: "Les cérémonies religieuses rythment la vie du village." },
    "Soleil+Récolte": { result: "Saisons", icon: "🍂", narration: "Le cycle des saisons est compris et respecté." },
    "Saisons+Prêtre": { result: "Calendrier", icon: "📅", narration: "Le calendrier religieux organise le temps." },
    "Calendrier+Agriculture": { result: "Cycle Agraire", icon: "🗓️", narration: "Le cycle agraire synchronise semailles et récoltes." },
    "Herbes+Chaman": { result: "Herboristerie", icon: "🌿", narration: "Le chaman maîtrise les plantes médicinales." },
    "Herboristerie+Humain": { result: "Guérisseur", icon: "👨‍⚕️", narration: "Le guérisseur soigne avec les plantes." },
    "Guérisseur+Mort": { result: "Médecine", icon: "🩺", narration: "La médecine primitive prend forme." },
    "Art Rupestre+Argile Cuite": { result: "Tablette d'Argile", icon: "📜", narration: "L'art devient écriture. Les premières tablettes d'argile gravées." },
    "Tablette d'Argile+Langage": { result: "Écriture", icon: "✍️", narration: "L'écriture naît ! L'humanité peut désormais transmettre au-delà de la parole. L'Histoire commence vraiment." },
    "Écriture+Échange": { result: "Registre", icon: "🧾", narration: "Les échanges sont consignés dans des registres." },
    "Écriture+Prêtre": { result: "Texte Sacré", icon: "📜", narration: "Les textes sacrés fixent les croyances pour l'éternité." },
    "Registre+Grenier": { result: "Administration", icon: "👑", narration: "L'administration naît pour gérer les stocks et les échanges." },
    "Administration+Village": { result: "Chef de Village", icon: "🧑‍⚖️", narration: "Un chef émerge pour diriger et administrer le village." },
    "Écriture+Croyance": { result: "Symbole", icon: "🕉️", narration: "Les symboles sacrés sont codifiés par l'écriture." },
    "Pain+Famille": { result: "Repas Partagé", icon: "🍲", narration: "Le pain partagé renforce les liens familiaux." },

    // Section 2.4 : Conflits et Expansion
    "Champ+Fermier": { result: "Propriété", icon: "🏡", narration: "La terre devient propriété. L'inégalité commence." },
    "Propriété+Village": { result: "Richesse", icon: "💰", narration: "Certains accumulent plus que d'autres. La richesse crée des classes." },
    "Richesse+Humain": { result: "Inégalité", icon: "👑", narration: "L'inégalité sociale s'installe durablement." },
    "Inégalité+Communauté": { result: "Conflit", icon: "⚔️", narration: "L'inégalité engendre tensions et conflits." },
    "Inégalité+Humain": { result: "Dette", icon: "💸", narration: "L'inégalité pousse certains à s'endetter auprès des riches." },
    "Dette+Humain": { result: "Esclavage", icon: "⛓️", narration: "Les dettes impayées mènent à l'esclavage." },
    "Conflit+Village": { result: "Palissade", icon: "🧱", narration: "Les villages se fortifient pour se protéger." },
    "Palissade+Village": { result: "Village Fortifié", icon: "🛡️", narration: "Les palissades transforment le village en forteresse." },
    "Village Fortifié+Conflit": { result: "Guerrier", icon: "🛡️", narration: "Des guerriers sont formés pour défendre le village." },
    "Guerrier+Lance": { result: "Milice", icon: "🛡️", narration: "Les guerriers s'organisent en milice." },
    "Bétail+Plaines": { result: "Pâturage", icon: "🌿", narration: "Les plaines deviennent pâturages pour le bétail." },
    "Pâturage+Éleveur": { result: "Nomade", icon: "🐎", narration: "Certains éleveurs restent nomades, suivant leurs troupeaux." },
    "Nomade+Campement": { result: "Tribu Nomade", icon: "🏕️", narration: "Les nomades forment des tribus mobiles." },
    "Tribu Nomade+Village": { result: "Raid", icon: "⚔️", narration: "Les nomades lancent des raids sur les villages sédentaires." },
    "Nomade+Animal": { result: "Cavalier", icon: "🐎", narration: "Le cheval domestiqué crée les premiers cavaliers." },
    "Palissade+Guerrier": { result: "Archer", icon: "🏹", narration: "Les archers défendent les remparts." },
    "Cavalier+Archer": { result: "Archer Monté", icon: "🐎", narration: "L'archer à cheval, redoutable guerrier mobile." },
    "Tribu Nomade+Archer Monté": { result: "Horde", icon: "🐎", narration: "Les hordes nomades déferlent sur les terres cultivées." },
    "Chef de Village+Chef de Village": { result: "Alliance Tribale", icon: "👑", narration: "Les chefs s'allient face aux menaces communes." },
    "Alliance Tribale+Conflit": { result: "Guerre Tribale", icon: "⚔️", narration: "Les alliances tribales s'affrontent dans des guerres." },
    "Guerre Tribale+Guerrier": { result: "Héros", icon: "🎖️", narration: "De la guerre émergent les héros." },
    "Héros+Mythe": { result: "Épopée", icon: "📜", narration: "Les exploits des héros deviennent épopées." },

    // ===== ÈRE 3 : ANTIQUE (LA CITÉ) =====

    // Section 3.1 : L'Âge du Métal
    "Minerai+Feu": { result: "Métal", icon: "⛓️", narration: "Le minerai fondu devient métal. L'âge du bronze commence. L'humanité entre dans l'Histoire." },
    "Métal+Outil Primitif": { result: "Outil en Métal", icon: "⚔️", narration: "Les outils en métal surpassent la pierre." },
    "Outil en Métal+Bois": { result: "Hache en Métal", icon: "🪓", narration: "La hache en métal abat les arbres avec une facilité inédite." },
    "Outil en Métal+Agriculture": { result: "Faucille", icon: "⛏️", narration: "La faucille en métal facilite la moisson." },
    "Métal+Feu": { result: "Forge", icon: "🏭", narration: "La forge devient le cœur de la production métallurgique." },
    "Forge+Artisan": { result: "Forgeron", icon: "👨‍🏭", narration: "Le forgeron maîtrise le feu et le métal. Un artisan respecté." },
    "Forgeron+Lance": { result: "Épée", icon: "🗡️", narration: "L'épée en métal devient l'arme des guerriers d'élite." },
    "Forgeron+Peau de Bête": { result: "Armure", icon: "🛡️", narration: "L'armure de cuir renforcé protège les combattants." },
    "Volcan+Feu": { result: "Minerai", icon: "⛏️", narration: "La chaleur intense révèle le minerai dans la roche." },
    "Métal+Minerai": { result: "Fer", icon: "⛓️", narration: "Le fer, plus dur que le bronze, révolutionne l'armement et l'outillage." },
    "Fer+Forgeron": { result: "Épée en Fer", icon: "⚔️", narration: "L'épée en fer, arme supérieure au bronze." },
    "Fer+Charrue": { result: "Charrue en Fer", icon: "⛏️", narration: "La charrue en fer laboure les terres les plus dures." },
    "Fer+Armure": { result: "Armure de Plaques", icon: "🛡️", narration: "L'armure de plaques métalliques rend le guerrier presque invincible." },
    "Chaleur+Bois": { result: "Charbon de Bois", icon: "🪨", narration: "Le bois carbonisé par la chaleur produit un charbon intense." },
    "Fer+Charbon de Bois": { result: "Acier", icon: "⛓️", narration: "Le fer raffiné devient acier, métal supérieur." },
    "Guerrier+Épée": { result: "Soldat", icon: "💂", narration: "Le guerrier tribal devient soldat professionnel." },
    "Soldat+Soldat": { result: "Armée", icon: "🎖️", narration: "Les soldats s'organisent en armées disciplinées." },
    "Armée+Fer": { result: "Légion", icon: "🛡️", narration: "Les légions en armure de fer dominent les champs de bataille." },

    // Section 3.2 : La Cité et l'Infrastructure
    "Village+Village Fortifié": { result: "Mur en Pierre", icon: "🧱", narration: "Les murs en pierre remplacent les palissades de bois." },
    "Mur en Pierre+Village": { result: "Cité", icon: "🏙️", narration: "Protégée par ses murs, la cité naît. Centre de pouvoir et de culture." },
    "Cité+Administration": { result: "Gouvernement", icon: "🏛️", narration: "Un gouvernement structuré administre la cité." },
    "Registre+Humain": { result: "Mathématiques", icon: "🧮", narration: "Les mathématiques naissent du besoin de compter et mesurer." },
    "Mathématiques+Sagesse Tribale": { result: "Savoir", icon: "🧠", narration: "Le savoir se structure et se transmet." },
    "Pierre+Mathématiques": { result: "Architecture", icon: "📐", narration: "L'architecture applique les mathématiques à la construction." },
    "Architecture+Cité": { result: "Monument", icon: "🏛️", narration: "Les monuments de pierre défient le temps." },
    "Architecture+Temple": { result: "Cathédrale", icon: "⛪", narration: "Les cathédrales s'élèvent vers le ciel, glorifiant les dieux." },
    "Corde+Roue": { result: "Poulie", icon: "🏗️", narration: "La roue et la corde créent la poulie qui multiplie la force humaine." },
    "Pierre+Bois": { result: "Levier", icon: "🏗️", narration: "Le levier soulève des charges impossibles." },
    "Poulie+Levier": { result: "Grue", icon: "🏗️", narration: "La grue primitive construit les grands édifices." },
    "Rivière+Roue": { result: "Roue à Aubes", icon: "🎡", narration: "La roue à aubes capte l'énergie de l'eau." },
    "Roue à Aubes+Farine": { result: "Moulin", icon: "🏭", narration: "Le moulin à eau moud la farine efficacement." },
    "Savoir+Eau": { result: "Hydrostatique", icon: "💧", narration: "La science de l'eau et de la pression naît." },
    "Hydrostatique+Architecture": { result: "Aqueduc", icon: "💧", narration: "Les aqueducs transportent l'eau sur de longues distances." },
    "Aqueduc+Cité": { result: "Bains Publics", icon: "🚿", narration: "Les bains publics deviennent centres sociaux." },
    "Bains Publics+Boue": { result: "Égouts", icon: "🚽", narration: "Les égouts évacuent les eaux usées." },
    "Égouts+Cité": { result: "Hygiène", icon: "🧼", narration: "L'hygiène publique améliore la santé urbaine." },

    // Section 3.3 : Gouvernance et Société
    "Armée+Cité": { result: "Conquête", icon: "⚔️", narration: "Les armées conquièrent les cités voisines." },
    "Conquête+Cité": { result: "Territoire", icon: "🗺️", narration: "Les conquêtes étendent le territoire contrôlé." },
    "Territoire+Gouvernement": { result: "Royaume", icon: "👑", narration: "Un royaume naît de l'unification des territoires." },
    "Royaume+Chef de Village": { result: "Roi", icon: "🤴", narration: "Le chef devient roi, souverain d'un royaume." },
    "Roi+Religion": { result: "Droit Divin", icon: "👑", narration: "Le roi règne par droit divin. Son pouvoir vient des dieux." },
    "Droit Divin+Roi": { result: "Monarchie Absolue", icon: "👑", narration: "La monarchie absolue concentre tous les pouvoirs dans les mains du roi." },
    "Monarchie Absolue+Conquête": { result: "Empire", icon: "🏛️", narration: "L'empire s'étend sur de vastes territoires. Une civilisation rayonnante naît." },
    "Empire+Humain": { result: "Esclavage Massif", icon: "⛓️", narration: "Les peuples conquis sont réduits en esclavage de masse." },
    "Esclavage Massif+Pierre": { result: "Pyramide", icon: "🏛️", narration: "Les esclaves construisent d'immenses pyramides." },
    "Écriture+Gouvernement": { result: "Loi", icon: "📜", narration: "Les lois écrites structurent la société." },
    "Loi+Humain": { result: "Justice", icon: "⚖️", narration: "La justice applique les lois pour tous." },
    "Justice+Gouvernement": { result: "Tribunal", icon: "🏛️", narration: "Les tribunaux jugent selon les lois établies." },
    "Marché+Cité": { result: "Guilde", icon: "🤝", narration: "Les marchands et artisans forment des guildes puissantes." },
    "Guilde+Artisan": { result: "Apprenti", icon: "🎓", narration: "Le système d'apprentissage transmet les savoirs artisanaux." },
    "Guilde+Gouvernement": { result: "Conseil", icon: "🏛️", narration: "Un conseil de notables conseille le gouvernement." },
    "Conseil+Tribunal": { result: "République", icon: "🏛️", narration: "La république naît, gouvernée par des citoyens libres." },
    "République+Loi": { result: "Citoyenneté", icon: "📜", narration: "La citoyenneté donne droits et devoirs." },
    "Citoyenneté+Humain": { result: "Débat Public", icon: "🗣️", narration: "Les citoyens débattent sur la place publique." },
    "République+Débat Public": { result: "Sénat", icon: "🏛️", narration: "Le sénat devient le cœur de la république." },
    "Sénat+Loi": { result: "Code de Loi", icon: "📜", narration: "Un code de loi universel structure l'empire." },
    "Grue+Mur en Pierre": { result: "Château Fort", icon: "🏰", narration: "Les châteaux forts dominent le paysage." },
    "Château Fort+Roi": { result: "Féodalisme", icon: "🏰", narration: "Le système féodal organise la société médiévale." },
    "Féodalisme+Fermier": { result: "Serf", icon: "🧑‍🌾", narration: "Les paysans deviennent serfs, liés à la terre." },
    "Cavalier+Armure de Plaques": { result: "Chevalier", icon: "🛡️", narration: "Le chevalier en armure, guerrier d'élite féodal." },
    "Chevalier+Féodalisme": { result: "Noblesse", icon: "👑", narration: "La noblesse, classe dirigeante féodale." },

    // Section 3.4 : Savoir et Culture
    "Savoir+Mathématiques": { result: "Savant", icon: "👨‍🏫", narration: "Le savant étudie les mystères du monde." },
    "Savant+Ciel": { result: "Astronomie", icon: "🔭", narration: "L'astronomie étudie les astres et leurs mouvements." },
    "Astronomie+Calendrier": { result: "Calendrier Solaire", icon: "🗓️", narration: "Le calendrier solaire précise le compte du temps." },
    "Débat Public+Savoir": { result: "Philosophie", icon: "🧠", narration: "La philosophie naît du questionnement rationnel. L'esprit humain s'éveille." },
    "Philosophie+Gouvernement": { result: "Politique", icon: "🏛️", narration: "La science politique étudie l'art de gouverner." },
    "Philosophie+Savoir": { result: "Raison", icon: "🧠", narration: "La raison structure la pensée humaine." },
    "Philosophie+Raison": { result: "Logique", icon: "🧠", narration: "La logique structure la pensée rationnelle." },
    "Texte Sacré+Écriture": { result: "Livre", icon: "📖", narration: "Les livres deviennent les gardiens du savoir." },
    "Livre+Gouvernement": { result: "Bibliothèque", icon: "🏫", narration: "Les bibliothèques conservent le savoir de l'humanité." },
    "Bibliothèque+Philosophie": { result: "Académie", icon: "🏫", narration: "Les académies forment les esprits brillants." },
    "Académie+Savant": { result: "Érudit", icon: "👨‍🔬", narration: "Les érudits maîtrisent de multiples disciplines." },
    "Bibliothèque+Savoir": { result: "Science", icon: "🔬", narration: "La science, méthode d'étude systématique du monde." },
    "Mathématiques+Terre": { result: "Géométrie", icon: "📐", narration: "La géométrie mesure et structure l'espace." },
    "Savant+Médecine": { result: "Médecin", icon: "👨‍⚕️", narration: "Le médecin soigne avec méthode et savoir." },
    "Médecin+Épée": { result: "Chirurgie", icon: "🔪", narration: "La chirurgie ouvre le corps pour soigner." },
    "Peinture+Cité": { result: "Art", icon: "🎨", narration: "L'art s'épanouit dans les cités." },
    "Art+Cité": { result: "Théâtre", icon: "🎭", narration: "Le théâtre devient art majeur des cités." },
    "Théâtre+Mythe": { result: "Tragédie", icon: "🎭", narration: "La tragédie raconte les mythes sur scène." },
    "Chant+Écriture": { result: "Poésie", icon: "✒️", narration: "La poésie écrite fixe les chants pour l'éternité." },
    "Art+Pierre": { result: "Sculpture", icon: "🗿", narration: "La sculpture immortalise les héros et les dieux." },
    "Philosophie+Croyance": { result: "Métaphysique", icon: "🤔", narration: "La métaphysique interroge l'essence de l'être." },

    // Section 3.5 : Commerce et Conflit
    "Rivière+Bois": { result: "Radeau", icon: "🛶", narration: "Le radeau permet de naviguer sur les rivières." },
    "Radeau+Tissu": { result: "Bateau à Voile", icon: "⛵", narration: "Les voiles propulsent les bateaux sur les océans." },
    "Bateau à Voile+Océan": { result: "Exploration", icon: "🗺️", narration: "Les explorateurs découvrent de nouvelles terres." },
    "Exploration+Marché": { result: "Route Commerciale", icon: "🛣️", narration: "Les routes commerciales relient les civilisations." },
    "Route Commerciale+Cité": { result: "Empire Maritime", icon: "🗺️", narration: "L'empire maritime domine les mers et le commerce." },
    "Empire Maritime+Conquête": { result: "Colonie", icon: "🚩", narration: "Les colonies étendent l'empire au-delà des mers." },
    "Route Commerciale+Métal": { result: "Monnaie", icon: "🪙", narration: "La monnaie métallique remplace le troc." },
    "Monnaie+Gouvernement": { result: "Impôt", icon: "💰", narration: "L'impôt finance l'État et ses armées." },
    "Monnaie+Marché": { result: "Économie", icon: "💸", narration: "L'économie monétaire structure les échanges." },
    "Économie+Guilde": { result: "Banque", icon: "🏦", narration: "Les banques prêtent et gèrent l'argent." },
    "Bateau à Voile+Armée": { result: "Marine", icon: "⚓", narration: "La marine de guerre domine les mers." },
    "Armée+Mur en Pierre": { result: "Siège", icon: "⚔️", narration: "Les armées assiègent les murs fortifiés." },
    "Siège+Bois": { result: "Bélier", icon: "🛡️", narration: "Le bélier enfonce les portes des cités." },
    "Siège+Pierre": { result: "Catapulte", icon: "🏹", narration: "La catapulte lance des projectiles sur les remparts." },
    "Art+Peinture": { result: "Pigment", icon: "🎨", narration: "Les pigments colorés enrichissent l'art." },

    // ===== ÈRE 4 : INDUSTRIELLE (LA RÉVOLUTION) =====

    // Section 4.1 : L'Âge de la Vapeur
    "Terre+Bois": { result: "Charbon", icon: "🪨", narration: "Le charbon fossile, énergie dense de l'ère industrielle." },
    "Charbon+Feu": { result: "Vapeur", icon: "💨", narration: "Le charbon chauffé produit une vapeur puissante." },
    "Vapeur+Métal": { result: "Machine à Vapeur", icon: "⚙️", narration: "La machine à vapeur ! La révolution industrielle gronde. L'humanité entre dans l'âge moderne." },
    "Science+Vapeur": { result: "Thermodynamique", icon: "🔬", narration: "La science de la chaleur et de l'énergie." },
    "Machine à Vapeur+Outil en Métal": { result: "Machinerie", icon: "🏭", narration: "Les machines multiplient la force humaine." },
    "Machinerie+Tissu": { result: "Métier à Tisser Mécanique", icon: "🏭", narration: "Le métier à tisser mécanique révolutionne le textile." },
    "Forge+Charbon": { result: "Haut Fourneau", icon: "🔥", narration: "Les hauts fourneaux produisent de l'acier en masse." },
    "Haut Fourneau+Acier": { result: "Aciérie", icon: "🏭", narration: "L'aciérie devient le cœur de l'industrie." },
    "Métier à Tisser Mécanique+Artisan": { result: "Usine", icon: "🏭", narration: "L'usine concentre machines et ouvriers. La production de masse commence." },
    "Usine+Cité": { result: "Ville Industrielle", icon: "🏙️", narration: "Les villes industrielles gonflent, polluées et grouillantes." },
    "Ville Industrielle+Ville Industrielle": { result: "Métropole", icon: "🌆", narration: "Les métropoles géantes dominent le paysage." },
    "Usine+Humain": { result: "Ouvrier", icon: "👷", narration: "Les paysans deviennent ouvriers d'usine." },
    "Ouvrier+Usine": { result: "Production de Masse", icon: "🏭", narration: "La production de masse inonde les marchés de biens." },
    "Machine à Vapeur+Bateau à Voile": { result: "Bateau à Vapeur", icon: "🚢", narration: "Les bateaux à vapeur sillonnent les océans sans dépendre du vent." },
    "Machine à Vapeur+Chariot": { result: "Locomotive", icon: "🚂", narration: "La locomotive à vapeur révolutionne le transport terrestre." },
    "Locomotive+Métal": { result: "Chemin de Fer", icon: "🛤️", narration: "Les chemins de fer relient les villes et les nations." },
    "Chemin de Fer+Ville Industrielle": { result: "Réseau de Transport", icon: "🌐", narration: "Un réseau de transport dense couvre les continents." },
    "Réseau de Transport+Économie": { result: "Marché Global", icon: "📈", narration: "L'économie devient mondiale." },
    "Usine+Charbon": { result: "Pollution", icon: "🏭", narration: "La pollution noircit le ciel des villes industrielles." },
    "Pollution+Ville Industrielle": { result: "Smog", icon: "🌫️", narration: "Le smog asphyxie les habitants des métropoles." },
    "Smog+Humain": { result: "Maladie", icon: "😷", narration: "Les maladies respiratoires frappent les populations urbaines." },
    "Maladie+Hygiène": { result: "Épidémie", icon: "☣️", narration: "Les épidémies se propagent dans les villes surpeuplées." },
    "Épidémie+Ville Industrielle": { result: "Hôpital", icon: "🏥", narration: "Les hôpitaux soignent les malades urbains." },

    // Section 4.2 : Idées et Changements Sociaux
    "Science+Livre": { result: "Presse à Imprimer", icon: "📇", narration: "La presse à imprimer diffuse le savoir en masse." },
    "Presse à Imprimer+Livre": { result: "Journal", icon: "📰", narration: "Les journaux informent et influencent l'opinion." },
    "Journal+Débat Public": { result: "Opinion Publique", icon: "🗣️", narration: "L'opinion publique devient une force politique." },
    "Science+Académie": { result: "Université", icon: "🎓", narration: "Les universités forment les scientifiques du futur." },
    "Université+Philosophie": { result: "Idée", icon: "💡", narration: "Les idées nouvelles circulent et bouleversent le monde." },
    "Idée+Opinion Publique": { result: "Philosophie des Lumières", icon: "🧠", narration: "La philosophie des Lumières proclame raison, liberté et progrès." },
    "Philosophie des Lumières+Monarchie Absolue": { result: "Révolution", icon: "💥", narration: "La révolution renverse les tyrans ! Le peuple se soulève." },
    "Révolution+Humain": { result: "Droits de l'Homme", icon: "📜", narration: "Les droits de l'homme sont proclamés universels." },
    "Droits de l'Homme+Gouvernement": { result: "Démocratie", icon: "🏛️", narration: "La démocratie donne le pouvoir au peuple." },
    "Démocratie+Loi": { result: "Constitution", icon: "📜", narration: "La constitution limite le pouvoir et protège les libertés." },
    "Idée+Humain": { result: "Psychologie", icon: "🧠", narration: "La psychologie étudie l'esprit humain." },
    "Humain+Opinion Publique": { result: "Suffragette", icon: "♀️", narration: "Les femmes luttent pour leurs droits." },
    "Esclavage+Révolution": { result: "Abolition", icon: "⛓️", narration: "L'esclavage est aboli par les révolutions." },
    "Gouvernement+Humain": { result: "Nationalisme", icon: "🌍", narration: "Le nationalisme unit les peuples en nations." },
    "Nationalisme+Colonie": { result: "Impérialisme", icon: "🌍", narration: "L'impérialisme étend les empires sur le monde." },
    "Science+Médecine": { result: "Biologie", icon: "🧬", narration: "La biologie étudie le vivant systématiquement." },
    "Science+Biologie": { result: "Évolution", icon: "🔬", narration: "La théorie de l'évolution révolutionne la biologie." },

    // Section 4.3 : Économie et Conflits Sociaux
    "Usine+Banque": { result: "Investissement", icon: "🏭", narration: "Les banques investissent dans l'industrie." },
    "Investissement+Richesse": { result: "Capital", icon: "💰", narration: "Le capital s'accumule entre les mains des industriels." },
    "Capital+Usine": { result: "Capitalisme", icon: "📈", narration: "Le capitalisme industriel domine l'économie." },
    "Capitalisme+Ouvrier": { result: "Salaire", icon: "💰", narration: "Les ouvriers vendent leur force de travail contre un salaire." },
    "Salaire+Inégalité": { result: "Pauvreté", icon: "🏚️", narration: "La pauvreté ouvrière côtoie la richesse des patrons." },
    "Capitalisme+Guilde": { result: "Corporation", icon: "🏢", narration: "Les corporations géantes dominent l'économie." },
    "Corporation+Économie": { result: "Bourse", icon: "📈", narration: "La bourse spécule sur l'avenir des entreprises." },
    "Bourse+Capital": { result: "Spéculation", icon: "💸", narration: "La spéculation financière crée des fortunes et des ruines." },
    "Spéculation+Bourse": { result: "Krach Boursier", icon: "📉", narration: "Les krachs boursiers ruinent des millions de gens." },
    "Ouvrier+Opinion Publique": { result: "Syndicat", icon: "✊", narration: "Les syndicats défendent les droits des travailleurs." },
    "Syndicat+Usine": { result: "Grève", icon: "🛑", narration: "La grève, arme des ouvriers contre l'exploitation." },
    "Grève+Idée": { result: "Socialisme", icon: "🚩", narration: "Le socialisme propose une alternative au capitalisme." },
    "Socialisme+Révolution": { result: "État Ouvrier", icon: "🏛️", narration: "L'État ouvrier prend le contrôle des moyens de production." },

    // Section 4.4 : Nouvelles Frontières
    "Science+Métal": { result: "Électricité", icon: "💡", narration: "L'électricité ! Une énergie propre et puissante. Le monde s'illumine." },
    "Sable+Feu": { result: "Verre", icon: "🥛", narration: "Le sable fondu devient verre transparent." },
    "Électricité+Verre": { result: "Ampoule", icon: "💡", narration: "L'ampoule chasse les ténèbres de la nuit." },
    "Ampoule+Ville Industrielle": { result: "Éclairage Public", icon: "🌃", narration: "L'éclairage public transforme les villes nocturnes." },
    "Électricité+Son": { result: "Télégraphe", icon: "📻", narration: "Le télégraphe transmet les messages instantanément." },
    "Télégraphe+Son": { result: "Téléphone", icon: "📞", narration: "Le téléphone permet de parler à distance." },
    "Télégraphe+Humain": { result: "Radio", icon: "📻", narration: "La radio diffuse les voix dans tous les foyers." },
    "Radio+Opinion Publique": { result: "Propagande de Masse", icon: "📰", narration: "La propagande utilise les médias de masse." },
    "Électricité+Machinerie": { result: "Moteur Électrique", icon: "⚡", narration: "Le moteur électrique remplace la vapeur." },
    "Moteur Électrique+Chariot": { result: "Automobile", icon: "🚗", narration: "L'automobile donne une liberté de mouvement inédite." },
    "Automobile+Route": { result: "Route Asphaltée", icon: "🛣️", narration: "Les routes asphaltées se multiplient pour les automobiles." },
    "Science+Pierre": { result: "Chimie", icon: "⚗️", narration: "La chimie décompose et recompose la matière." },
    "Chimie+Science": { result: "Laboratoire", icon: "🧪", narration: "Le laboratoire permet d'expérimenter et découvrir." },
    "Laboratoire+Chimie": { result: "Dynamite", icon: "💥", narration: "La dynamite révolutionne la construction et la guerre." },
    "Chimie+Armée": { result: "Poudre à Canon", icon: "💣", narration: "La poudre à canon rend les armées dévastatrices." },
    "Poudre à Canon+Métal": { result: "Arme à Feu", icon: "🔫", narration: "Les armes à feu changent à jamais la guerre." },
    "Arme à Feu+Armée": { result: "Guerre Moderne", icon: "💥", narration: "La guerre moderne est industrielle et meurtrière." },
    "Guerre Moderne+Guerre Moderne": { result: "Guerre Mondiale", icon: "🌍", narration: "Les guerres mondiales embrasent la planète entière." },
    "Guerre Mondiale+Gouvernement": { result: "Nations Unies", icon: "🌐", narration: "Les nations s'unissent pour préserver la paix." },
    "Chimie+Agriculture": { result: "Engrais Chimique", icon: "🌾", narration: "Les engrais chimiques dopent les récoltes." },
    "Engrais Chimique+Récolte Abondante": { result: "Explosion Démographique", icon: "📈", narration: "La population mondiale explose grâce à l'abondance." },
    "Biologie+Médecine": { result: "Médecine Moderne", icon: "🩺", narration: "La biologie et la médecine fusionnent pour sauver des millions de vies." },
    "Médecine Moderne+Verre": { result: "Microscope", icon: "🔬", narration: "Le microscope révèle l'invisible." },
    "Microscope+Médecine Moderne": { result: "Bactérie", icon: "🦠", narration: "Les bactéries, invisibles ennemis, sont découvertes." },
    "Bactérie+Médecine Moderne": { result: "Vaccin", icon: "💉", narration: "Les vaccins éradiquent les grandes épidémies." },
    "Vaccin+Humain": { result: "Santé Publique", icon: "❤️", narration: "La santé publique améliore l'espérance de vie." },
    "Science+Chaleur": { result: "Physique", icon: "⚖️", narration: "La physique étudie les lois de l'univers." },
    "Physique+Science": { result: "Aérodynamique", icon: "✈️", narration: "L'aérodynamique permet de comprendre le vol." },
    "Aérodynamique+Machine à Vapeur": { result: "Avion", icon: "✈️", narration: "L'avion ! L'homme conquiert le ciel. Le rêve d'Icare réalisé." },
    "Avion+Guerre Moderne": { result: "Combat Aérien", icon: "✈️", narration: "Les avions de combat dominent le ciel." },
    "Art+Science": { result: "Photographie", icon: "📷", narration: "La photographie capture l'instant pour l'éternité." },
    "Photographie+Machinerie": { result: "Cinéma", icon: "🎬", narration: "Le cinéma, le septième art, fait rêver les foules." },
    "Électricité+Réseau de Transport": { result: "Réseau Électrique", icon: "⚡", narration: "Le réseau électrique alimente les villes." },
    "Moteur Électrique+Transport": { result: "Tramway", icon: "🚃", narration: "Le tramway électrique sillonne les rues." },

    // ===== ÈRE 5 : SPATIALE (LE FUTUR) =====

    // Section 5.1 : L'Âge de l'Information
    "Électricité+Mathématiques": { result: "Ordinateur", icon: "💻", narration: "L'ordinateur ! La machine pensante. L'humanité crée l'intelligence artificielle." },
    "Ordinateur+Ordinateur": { result: "Réseau", icon: "🌐", narration: "Les ordinateurs se connectent en réseaux." },
    "Réseau+Téléphone": { result: "Téléphone Portable", icon: "📱", narration: "Le téléphone portable connecte chacun au monde entier." },
    "Réseau+Université": { result: "Internet", icon: "🌍", narration: "Internet ! Le réseau mondial unifie l'humanité dans un village global." },
    "Ordinateur+Écriture": { result: "Langage de Programmation", icon: "⌨️", narration: "Les langages de programmation permettent de parler aux machines." },
    "Ordinateur+Internet": { result: "Cloud Computing", icon: "☁️", narration: "Le cloud stocke les données dans les nuages numériques." },
    "Sable+Électricité": { result: "Puce de Silicium", icon: "💻", narration: "La puce de silicium miniaturise l'informatique." },
    "Puce de Silicium+Ordinateur": { result: "Micro-ordinateur", icon: "💻", narration: "Le micro-ordinateur met la puissance de calcul à portée de tous." },
    "Ordinateur+Monnaie": { result: "Cryptomonnaie", icon: "₿", narration: "La cryptomonnaie décentralise la finance." },
    "Internet+Humain": { result: "Société de l'Information", icon: "📱", narration: "La société de l'information transforme tous les aspects de la vie." },
    "Internet+Économie": { result: "Commerce Électronique", icon: "🛒", narration: "Le commerce électronique révolutionne la distribution." },
    "Internet+Marché Global": { result: "Globalisation", icon: "🌍", narration: "La globalisation interconnecte toutes les économies." },
    "Internet+Opinion Publique": { result: "Réseaux Sociaux", icon: "📱", narration: "Les réseaux sociaux donnent une voix à chacun." },
    "Réseaux Sociaux+Politique": { result: "Cyber-propagande", icon: "📣", narration: "La cyber-propagande manipule l'opinion en ligne." },
    "Internet+Conflit": { result: "Cybersécurité", icon: "🛡️", narration: "La cybersécurité protège contre les attaques numériques." },
    "Cybersécurité+Humain": { result: "Hacker", icon: "🕵️", narration: "Les hackers explorent les failles des systèmes." },
    "Hacker+Réseau": { result: "Virus Informatique", icon: "🦠", narration: "Les virus informatiques infectent les réseaux." },
    "Ordinateur+Réseau": { result: "Réalité Virtuelle", icon: "🕶️", narration: "La réalité virtuelle crée des mondes numériques immersifs." },
    "Réalité Virtuelle+Réseaux Sociaux": { result: "Métavers", icon: "🌐", narration: "Le métavers fusionne réel et virtuel." },

    // Section 5.2 : L'Ère de l'IA
    "Ordinateur+Savoir": { result: "Intelligence Artificielle", icon: "🤖", narration: "L'intelligence artificielle ! Les machines pensent. Une nouvelle forme de conscience naît." },
    "Intelligence Artificielle+Outil en Métal": { result: "IA Faible", icon: "🤖", narration: "L'IA faible excelle dans des tâches spécifiques." },
    "Intelligence Artificielle+Usine": { result: "Automatisation", icon: "🤖", narration: "L'automatisation remplace le travail humain." },
    "Automatisation+Ouvrier": { result: "Chômage", icon: "🚫", narration: "Le chômage technologique frappe les travailleurs." },
    "Intelligence Artificielle+Science": { result: "Réseau Neuronal", icon: "🧠", narration: "Les réseaux neuronaux imitent le cerveau humain." },
    "Réseau Neuronal+Intelligence Artificielle": { result: "IA Forte", icon: "🤖", narration: "L'IA forte atteint une intelligence générale." },
    "IA Forte+Automatisation": { result: "Robot", icon: "🤖", narration: "Les robots autonomes peuplent le monde." },
    "Robot+Humain": { result: "Serviteur Robot", icon: "🤖", narration: "Les robots deviennent serviteurs de l'humanité." },
    "Robot+IA Forte": { result: "Conscience Synthétique", icon: "🤖", narration: "Une conscience synthétique émerge dans les machines." },
    "Conscience Synthétique+Internet": { result: "IA Globale", icon: "🤖", narration: "Une IA globale unifie toutes les intelligences artificielles." },
    "IA Globale+Humain": { result: "Singularité", icon: "🌌", narration: "La Singularité ! L'humanité et la machine fusionnent. Rien ne sera plus jamais pareil." },
    "Justice+IA Forte": { result: "Lois de la Robotique", icon: "📜", narration: "Des lois encadrent les intelligences artificielles." },
    "Science+Atome": { result: "Physique Quantique", icon: "⚛️", narration: "La science de l'atome révèle la physique quantique, exploration de l'infiniment petit." },
    "Ordinateur+Physique Quantique": { result: "Ordinateur Quantique", icon: "💻", narration: "L'ordinateur quantique décuple la puissance de calcul." },
    "Ordinateur Quantique+IA Forte": { result: "Super-IA", icon: "🧠", narration: "La super-IA dépasse l'intelligence humaine." },

    // Section 5.3 : La Conquête Spatiale
    "Atome+Science": { result: "Physique Nucléaire", icon: "⚛️", narration: "L'étude scientifique de l'atome dévoile la physique nucléaire." },
    "Physique Nucléaire+Lumière": { result: "Énergie Nucléaire", icon: "☢️", narration: "L'énergie nucléaire libère une puissance colossale." },
    "Énergie Nucléaire+Guerre Moderne": { result: "Bombe Atomique", icon: "💣", narration: "La bombe atomique peut annihiler l'humanité. L'ère nucléaire commence dans la terreur." },
    "Bombe Atomique+Politique": { result: "Guerre Froide", icon: "🤝", narration: "La Guerre Froide oppose les blocs dans une paix armée." },
    "Physique Nucléaire+Machinerie": { result: "Centrale Nucléaire", icon: "🏭", narration: "Les centrales nucléaires produisent de l'électricité en masse." },
    "Énergie Nucléaire+Science": { result: "Fusion Nucléaire", icon: "💡", narration: "La science avancée maîtrise la fusion nucléaire, énergie quasi-illimitée." },
    "Fusion Nucléaire+Humain": { result: "Énergie Illimitée", icon: "💡", narration: "L'énergie illimitée résout la crise énergétique." },
    "Science+Avion": { result: "Fusée", icon: "🚀", narration: "La fusée ! L'humanité quitte la Terre. L'espace s'ouvre à nous." },
    "Fusée+Conquête": { result: "Conquête Spatiale", icon: "🚀", narration: "L'humanité conquiert l'espace." },
    "Guerre Froide+Conquête Spatiale": { result: "Course à la Lune", icon: "🌕", narration: "La course à la Lune oppose les superpuissances." },
    "Fusée+Métal": { result: "Satellite", icon: "🛰️", narration: "Les satellites orbitent autour de la Terre." },
    "Satellite+Internet": { result: "Communication Globale", icon: "📡", narration: "Les communications par satellite couvrent le globe." },
    "Fusée+Humain": { result: "Astronaute", icon: "🧑‍🚀", narration: "Les astronautes, nouveaux explorateurs de l'infini." },
    "Astronaute+Fusée": { result: "Station Spatiale", icon: "🛰️", narration: "La station spatiale, avant-poste de l'humanité dans l'espace." },
    "Station Spatiale+Humain": { result: "Colonie Spatiale", icon: "🚀", narration: "Les colonies spatiales s'installent hors de la Terre." },
    "Colonie Spatiale+Terre": { result: "Terraformation", icon: "🪐", narration: "La terraformation rend les planètes habitables." },
    "Colonie Spatiale+Terraformation": { result: "Colonisation de Mars", icon: "🪐", narration: "Mars est colonisée ! L'humanité devient multi-planétaire." },
    "Fusion Nucléaire+Fusée": { result: "Voyage Interstellaire", icon: "🚀", narration: "Le voyage interstellaire ouvre la galaxie à l'exploration." },
    "Voyage Interstellaire+Biologie": { result: "Exobiologie", icon: "👽", narration: "La recherche de vie extraterrestre commence." },
    "Monument+Énergie Illimitée": { result: "Sphère de Dyson", icon: "✨", narration: "La sphère de Dyson capte toute l'énergie d'une étoile." },
    "Fusée+Science": { result: "Sonde", icon: "🛰️", narration: "Les sondes explorent le système solaire." },
    "Ciel+Terre": { result: "Planète", icon: "🌍", narration: "La Terre, notre planète dans l'immensité." },
    "Planète+Sonde": { result: "Mars", icon: "🪐", narration: "Mars, la planète rouge, cible de la colonisation." },

    // Section 5.4 : Biotechnologie et Transhumanisme
    "Science+Évolution": { result: "Génétique", icon: "🧬", narration: "La génétique décode l'ADN, le code de la vie." },
    "Génétique+Ordinateur": { result: "Séquençage ADN", icon: "🧬", narration: "Le séquençage ADN lit le génome complet." },
    "Génétique+Agriculture": { result: "OGM", icon: "🌽", narration: "Les OGM modifient génétiquement les cultures." },
    "Génétique+Humain": { result: "Modification Génétique", icon: "🧬", narration: "La modification génétique permet de réécrire l'humain." },
    "Modification Génétique+Outil en Métal": { result: "CRISPR", icon: "🧬", narration: "CRISPR, les ciseaux génétiques, éditent l'ADN avec précision." },
    "Modification Génétique+Médecine Moderne": { result: "Thérapie Génique", icon: "💉", narration: "La thérapie génique guérit les maladies génétiques." },
    "Génétique+Séquençage ADN": { result: "Clonage", icon: "🐏", narration: "Le clonage reproduit des êtres vivants identiques." },
    "Clonage+Loi": { result: "Éthique", icon: "⚖️", narration: "L'éthique encadre les avancées scientifiques." },
    "Thérapie Génique+Humain": { result: "Longévité", icon: "📈", narration: "La longévité humaine s'étend considérablement." },
    "Longévité+Modification Génétique": { result: "Immortalité", icon: "⏳", narration: "L'immortalité biologique devient possible. La mort n'est plus une fatalité." },
    "Ordinateur+Psychologie": { result: "Cerveau", icon: "🧠", narration: "Le cerveau, ordinateur biologique étudié scientifiquement." },
    "Ordinateur+Cerveau": { result: "Interface Cerveau-Machine", icon: "🧠", narration: "L'interface cerveau-machine connecte l'esprit aux ordinateurs." },
    "Interface Cerveau-Machine+Humain": { result: "Transhumanisme", icon: "🦾", narration: "Le transhumanisme augmente les capacités humaines." },
    "Transhumanisme+Singularité": { result: "Conscience Collective", icon: "🧠", narration: "La conscience collective fusionne les esprits." },
    "Conscience Collective+Internet": { result: "Noosphère", icon: "🌐", narration: "La noosphère, sphère de la pensée globale, englobe la Terre." },
    "Interface Cerveau-Machine+Cloud Computing": { result: "Téléchargement de Conscience", icon: "🧠", narration: "Le téléchargement de conscience rend l'esprit immortel dans le numérique." },
    "Immortalité+Téléchargement de Conscience": { result: "Post-Humanité", icon: "👻", narration: "L'ère post-humaine commence. L'humanité transcende sa forme biologique." },
    "Science+Physique Nucléaire": { result: "Atome", icon: "⚛️", narration: "L'atome, brique fondamentale de la matière." },
    "Physique Quantique+Atome": { result: "Nanotechnologie", icon: "🔬", narration: "La physique quantique appliquée à l'atome permet de manipuler l'infiniment petit." },
    "Nanotechnologie+Médecine Moderne": { result: "Nanorobot", icon: "🤖", narration: "Les nanorobots soignent depuis l'intérieur du corps." },
    "Biologie+Évolution": { result: "Vie", icon: "🧬", narration: "La vie, mystère scientifique exploré." },

    // Section 5.5 : L'Avenir de la Planète
    "Pollution+Planète": { result: "Réchauffement Climatique", icon: "🌡️", narration: "Le réchauffement climatique menace la planète." },
    "Réchauffement Climatique+Science": { result: "Climatologie", icon: "🔬", narration: "La climatologie étudie le changement climatique." },
    "Climatologie+Opinion Publique": { result: "Mouvement Écologiste", icon: "♻️", narration: "Le mouvement écologiste se bat pour sauver la planète." },
    "Mouvement Écologiste+Gouvernement": { result: "Politique Verte", icon: "♻️", narration: "La politique verte intègre l'écologie au pouvoir." },
    "Soleil+Science": { result: "Énergie Solaire", icon: "☀️", narration: "L'énergie solaire exploite la puissance du Soleil." },
    "Ciel+Machinerie": { result: "Vent", icon: "🌬️", narration: "Le vent, énergie renouvelable captée par les machines." },
    "Vent+Machinerie": { result: "Énergie Éolienne", icon: "🌬️", narration: "L'énergie éolienne capte la force du vent." },
    "Énergie Solaire+Énergie Éolienne": { result: "Énergie Renouvelable", icon: "♻️", narration: "Les énergies renouvelables remplacent les fossiles." },
    "Énergie Renouvelable+Ville Industrielle": { result: "Éco-cité", icon: "🌳", narration: "Les éco-cités vivent en harmonie avec la nature." },
    "Climatologie+Science": { result: "Géo-ingénierie", icon: "🌍", narration: "La science climatique avancée permet la géo-ingénierie, manipulation du climat planétaire." },
    "Géo-ingénierie+Éthique": { result: "Controverse", icon: "🚫", narration: "La géo-ingénierie soulève des controverses éthiques." },
    "Gouvernement+Internet": { result: "Gouvernement Mondial", icon: "🌍", narration: "Un gouvernement mondial unifie l'humanité." },
    "Gouvernement Mondial+Corporation": { result: "Cyber-corporatocratie", icon: "🌍", narration: "Les corporations dominent le gouvernement mondial." },
    "Gouvernement Mondial+IA Globale": { result: "Dystopie", icon: "🤖", narration: "La dystopie : un monde contrôlé par les machines et le pouvoir absolu." },
    "Gouvernement Mondial+Fusion Nucléaire": { result: "Utopie", icon: "🌟", narration: "L'utopie : un monde d'abondance, de paix et de progrès infini. Le rêve de l'humanité réalisé." }
};

// Export pour utilisation dans les fichiers HTML
if (typeof module !== 'undefined' && module.exports) {
    module.exports = COMBINATIONS;
}
